version: "3"
services:
  graphcache-go:
    image: graphcache-go
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./_data:/app/_data
    environment:
      - UNISWAP_CANDLES=true
